# **PyTorch Fundamentals**

---

## **Learning Objectives**

1. **Understand** the fundamental concepts of tensors and their role in deep learning
2. **Create** and manipulate tensors using PyTorch's tensor operations
3. **Apply** tensor operations for mathematical computations in deep learning contexts
4. **Implement** tensor reshaping, indexing, and aggregation operations
5. **Utilize** GPU acceleration for tensor computations
6. **Debug** common tensor-related errors in PyTorch applications

---

- Basic understanding of Python programming
- Familiarity with NumPy arrays (recommended)
- Linear algebra fundamentals (vectors, matrices, matrix multiplication)
- Basic machine learning concepts (recommended but not required)

## **1. Overview and Theoretical Background**

### **1.1 Introduction to PyTorch**

[PyTorch](https://pytorch.org/) is an open-source machine learning framework developed by Facebook's AI Research lab (FAIR). It provides a Python-based scientific computing package that serves as:

1. **A replacement for NumPy** with the power of Graphics Processing Units (GPUs)
2. **A deep learning research platform** that provides maximum flexibility and speed


### **1.2 Advantages of PyTorch**

**Research-Friendly Design**:
- Dynamic computational graphs allow for flexible model architectures
- Pythonic interface that integrates seamlessly with the Python ecosystem
- Extensive debugging capabilities with standard Python debugging tools

**Performance Optimization**:
- Efficient GPU utilization through CUDA integration
- Optimized tensor operations for numerical computations
- Support for distributed training across multiple devices

### **1.3 Theoretical Foundation: Understanding Tensors**

**Tensors** represent the fundamental data structure in machine learning and deep learning applications. They serve as generalized mathematical objects that can represent:

- **Scalars** (0-dimensional tensors): Single numerical values
- **Vectors** (1-dimensional tensors): Arrays of numbers with directional properties
- **Matrices** (2-dimensional tensors): Rectangular arrays for linear transformations
- **Higher-order tensors** (n-dimensional): Multi-dimensional data structures for complex data


### **1.4 Curriculum Structure**

This tutorial systematically covers the essential tensor operations required for deep learning applications:

| **Module** | **Learning Outcomes** | **Practical Applications** |
|------------|----------------------|---------------------------|
| **2. Tensor Introduction** | Understand tensor mathematics and data representation | Foundation for all ML/DL operations |
| **3. Tensor Creation** | Master various tensor initialization methods | Data preprocessing and model initialization |
| **4. Tensor Introspection** | Extract metadata and properties from tensors | Debugging and model analysis |
| **5. Tensor Operations** | Perform mathematical operations on tensors | Forward and backward propagation in neural networks |
| **6. Shape Manipulation** | Reshape and reorganize tensor dimensions | Data preprocessing and model compatibility |
| **7. Tensor Indexing** | Access and modify specific tensor elements | Data sampling and feature extraction |
| **8. NumPy Integration** | Convert between PyTorch tensors and NumPy arrays | Interoperability with existing data science workflows |
| **9. Reproducibility** | Control randomness for consistent results | Ensuring reproducible research and debugging |
| **10. GPU Acceleration** | Leverage GPU computing for faster operations | Scaling computations for large datasets and models |


### **1.5 Mathematical Notation**

Throughout this tutorial, we will use the following mathematical conventions:

- **Scalars**: Lowercase italic letters (e.g., *x*, *y*, *α*)
- **Vectors**: Lowercase bold letters (e.g., **x**, **v**)
- **Matrices**: Uppercase bold letters (e.g., **X**, **W**)
- **Tensors**: Uppercase bold letters with tensor rank notation (e.g., **𝒳** ∈ ℝᵈ¹ˣᵈ²ˣ...ˣᵈⁿ)

## **2. Environment Setup and Library Imports**

### **2.3 Library Import and Version Verification**

We begin by importing the PyTorch library and verifying the installed version. This step ensures compatibility and helps with debugging potential version-specific issues.

In [33]:
# Import the PyTorch library
# PyTorch is the primary library for tensor operations and deep learning
import torch

# Display the PyTorch Version
# This is crucial for ensuring compatibility with code examples
# Different PyTorch versions may have slight API differences
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.9.0+cpu


## **3. Introduction to Tensors: Mathematical Foundations**

### **3.1 Theoretical Background**

**Tensors constitute the fundamental building blocks of machine learning computations.** In the context of deep learning, tensors serve as the primary data structure for representing:

- **Input data**: Images, text sequences, audio signals, and tabular data
- **Model parameters**: Weights and biases in neural networks
- **Intermediate computations**: Activations and gradients during training
- **Output predictions**: Classification probabilities and regression values

### **3.2 Mathematical Definition**

A tensor **T** of rank **n** (or order **n**) is a mathematical object with **n** indices, where each index can range over a specific dimension. Formally:

**T** ∈ ℝᵈ¹ˣᵈ²ˣ...ˣᵈⁿ

Where:
- **d₁, d₂, ..., dₙ** represent the size of each dimension
- **n** is the rank/order of the tensor
- **ℝ** denotes the set of real numbers (though tensors can contain other data types)

### **3.3 Computational Significance**

Tensors enable efficient computation through:

1. **Vectorization**: Operations on entire arrays rather than individual elements
2. **Parallelization**: GPU acceleration for simultaneous computations
3. **Automatic Differentiation**: Gradient computation for optimization algorithms
4. **Memory Efficiency**: Optimized storage and access patterns

## **4. Tensor Creation and Initialization Methods**

### **4.1 Theoretical Framework**

The [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) class serves as the fundamental data structure in PyTorch. Understanding tensor creation methods is crucial for:

- **Data preprocessing**: Converting raw data into tensor format
- **Model initialization**: Creating parameter tensors with appropriate shapes
- **Experimentation**: Generating synthetic data for testing and validation

### **4.2 Tensor Hierarchy and Classification**

**4.2.1 Scalar Tensors (Rank 0)**

A **scalar** represents a single numerical value and constitutes a **zero-dimensional tensor**. In mathematical notation:
- **Mathematical representation**: *s* ∈ ℝ
- **PyTorch shape**: `torch.Size([])`
- **Dimensions**: 0

**Properties:**
- Contains exactly one element
- No directional information
- Often used for loss values, learning rates, and single metrics

In [34]:
# Create a scalar tensor (0-dimensional tensor)
# Scalars contains a single numerical value and have no dimensions
# They are fundamental building blocks for more complex tensor operations

scalar = torch.tensor(7)  # Create a scalar with value 7

# Display the scalar tensor
print(f"Scalar tensor: {scalar}")
print(f"Scalar value: {scalar.item()}")  #Extract the python number
print(f"Data type: {scalar.dtype}")    # Check the data type
print(f"Shape: {scalar.shape}")          # Shape is empty for scalars
print(f"Size: {scalar.size()}")          # Alternative way to check shape

# The scalar tensor object contains metadata beyond just the value:
# - dtype: The daata type (default is inferred from input)
#  - device: The computational device (CPU or GPU)
#  -requires_grad: Whether to track gradients for automatic differentiation

scalar

Scalar tensor: 7
Scalar value: 7
Data type: torch.int64
Shape: torch.Size([])
Size: torch.Size([])


tensor(7)

### **4.3 Tensor Dimensionality Analysis**

**Tensor dimensionality** (or rank) indicates the number of indices required to specify an element within the tensor. The `ndim` attribute provides this crucial information for tensor manipulation and debugging.

In [35]:
# Check the number of dimensions (rank) of the scalar tensor
# For a scalar, this should return 0 since it has no dimensions
dimensionality = scalar.ndim

print(f"Number of dimensions (rank): {dimensionality}")
print(f"Verification: A scalar has {dimensionality} dimensions")

# Understanding dimensions is crucial for :
# 1. Matrix operations (shapes must be comptatible)
# 2. Neural network layer design (input/output dimensions must match)
# 3. Data preprocessing (ensuring correct tensor shapes)

dimensionality

Number of dimensions (rank): 0
Verification: A scalar has 0 dimensions


0

### **4.4 Value Extraction from Tensors**

To retrieve the underlying numerical value from a tensor, PyTorch provides the `item()` method. This method is essential for:

- **Metric reporting**: Extracting loss values for logging
- **Conditional operations**: Using tensor values in Python control structures  
- **Debugging**: Inspecting individual tensor elements

**Important constraint**: The `item()` method only works with tensors containing exactly one element (single-element tensors).

In [36]:
# Extract the Python numerical value from a single-element tensor
# The item() method converts a PyTorch tensor to a Python scalar
# This is essential when you need to use tensor values in standard Python operations

python_value = scalar.item()

print(f"Original tensor: {scalar}")
print(f"Extracted Python Value: {python_value}")
print(f"Type of Tensor: {type(scalar)}")
print(f"Type of extracted value: {type(python_value)}")

# Practical applications of item():
# 1. Loss monitoring: loss_value = loss_tensor.item()
# 2. Metric computation: accuracy = correct_predictions.item() / total_samples
# 3. Conditional logic: if accuracy_tensor.item() > threshold: ...
# 4. Logging: print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# Note: Attempting item() on multi-element tensors will raise an error
# For multi-element tensors, use indexing to access specific elements first

python_value

Original tensor: 7
Extracted Python Value: 7
Type of Tensor: <class 'torch.Tensor'>
Type of extracted value: <class 'int'>


7

### **4.5 Vector Tensors (Rank 1)**

#### **4.5.1 Mathematical Definition**

A **vector** represents a one-dimensional tensor containing multiple numerical values arranged in a specific order. In mathematical notation:
- **Mathematical representation**: **v** ∈ ℝⁿ
- **PyTorch shape**: `torch.Size([n])`  
- **Dimensions**: 1

In [37]:
# Create a vector tensor (1-dimensional tensor)
# Vectors contain multiple values arranged in a single dimension
# They are fundamental for representing sequences, features and embeddings

vector = torch.tensor([7.0, 7.0])   # Create a vector with two identical elements

print(f"Vector tensor: {vector}")
print(f"Data type: {type(vector)}")
print(f"Dimension: {vector.dim()}")
print(f"Shape: {vector.shape}")
print(f"Number of elements: {vector.numel()}")   # Total number of elements

# Vector interpretation examples:
# [7, 7] could represent:
# - Coordinates in 2D space (x=7, y=7)
# - Two identical measurements
# - A repeated pattern or signal
# - Feature values for two attributes

# Mathematical properties:
print(f"L2 norm (Euclidean length): {torch.norm(vector).item():.4f}")
print(f"Sum of elements: {torch.sum(vector).item()}")
print(f"Mean of elements: {torch.mean(vector.float()).item():.4f}")

vector

Vector tensor: tensor([7., 7.])
Data type: <class 'torch.Tensor'>
Dimension: 1
Shape: torch.Size([2])
Number of elements: 2
L2 norm (Euclidean length): 9.8995
Sum of elements: 14.0
Mean of elements: 7.0000


tensor([7., 7.])

### **4.6 Matrix Tensors (Rank 2)**

**Mathematical Definition:**
A **matrix** represents a two-dimensional tensor organized in rows and columns. In mathematical notation:
- **Mathematical representation**: **M** ∈ ℝᵐˣⁿ
- **PyTorch shape**: `torch.Size([m, n])`
- **Dimensions**: 2

**Properties:**
- **Rows (m)**: First dimension, representing horizontal sequences
- **Columns (n)**: Second dimension, representing vertical sequences  
- **Linear transformations**: Matrices can represent linear mappings between vector spaces
- **Data organization**: Natural structure for tabular data and 2D relationships

In [38]:
# Create a matrix tensor (2-dimensional tensor)
# Matrices are fundamental for linear algebra operations in machine learning
# They represent linear transformations, weight matrices, and 2D data structures

MATRIX = torch.tensor([[7.0, 8.0],                   # First row: [7, 8]
                       [9.0, 10.0]])                 # Second row: [9, 10]

print(f"Matrix tensor:\n{MATRIX}")
print(f"Data type: {MATRIX.dtype}")
print(f"Dimension: {MATRIX.dim()}")  # Should return 2 for a matrix
print(f"Shape: {MATRIX.shape}")  # Returns torch.Size([rows, columns])
print(f"Number of dimensions: {MATRIX.ndim}")
print(f"Total elements: {MATRIX.numel()}")

# Matrix properties and operations:
print(f"\nMatrix properties:")
print(f"Determinant: {torch.det(MATRIX.float()).item():.4f}")  # Requires float type
print(f"Trace (sum of diagonal): {torch.trace(MATRIX).item()}")
print(f"Frobenius norm: {torch.norm(MATRIX).item():.4f}")

# Matrix interpretations:
# - Weight matrix in neural networks (input_features × output_features)
# - Transformation matrix for geometric operations
# - Correlation matrix for feature relationships
# - Adjacency matrix for graph representations

MATRIX

Matrix tensor:
tensor([[ 7.,  8.],
        [ 9., 10.]])
Data type: torch.float32
Dimension: 2
Shape: torch.Size([2, 2])
Number of dimensions: 2
Total elements: 4

Matrix properties:
Determinant: -2.0000
Trace (sum of diagonal): 17.0
Frobenius norm: 17.1464


tensor([[ 7.,  8.],
        [ 9., 10.]])

### **4.7 Higher-Order Tensors (Rank ≥ 3)**

**Mathematical Definition:**
Higher-order tensors extend beyond matrices to represent multi-dimensional data structures. For a rank-3 tensor:
- **Mathematical representation**: **𝒯** ∈ ℝᵈ¹ˣᵈ²ˣᵈ³
- **PyTorch shape**: `torch.Size([d1, d2, d3])`
- **Dimensions**: 3 or higher

**Applications in Deep Learning:**
- **Batch processing**: `[batch_size, features]` or `[batch_size, channels, height, width]`
- **Sequence modeling**: `[batch_size, sequence_length, feature_dimension]`
- **Computer vision**: `[batch_size, channels, height, width]` for image batches
- **Video processing**: `[batch_size, time_steps, channels, height, width]`

In [39]:
# Create a higher-order tensor (3-dimensional tensor)
# This example creates a rank-3 tensor with shape [1, 3, 3]
# The triple bracket notation [[[...]]] indicates three dimensions

TENSOR = torch.tensor([[[1, 2, 3],     # First 3x3 matrix, row 1
                        [3, 6, 9],     # First 3x3 matrix, row 2
                        [2, 4, 5]]])   # First 3x3 matrix, row 3

print(f"3D Tensor:\n{TENSOR}")
print(f"Data type: {TENSOR.dtype}")
print(f"Dimension: {TENSOR.dim()}")  # Should return 3 for a 3D tensor
print(f"Shape: {TENSOR.shape}")  # torch.Size([1, 3, 3])
print(f"Number of dimensions: {TENSOR.ndim}")
print(f"Total elements: {TENSOR.numel()}")

# Shape interpretation: [1, 3, 3]
# - Dimension 0: 1 "slice" or "channel" (outermost dimension)
# - Dimension 1: 3 rows within each slice
# - Dimension 2: 3 columns within each row

print(f"\nDimensional analysis:")
print(f"Outer dimension (axis 0): {TENSOR.shape[0]} - Number of 3x3 matrices")
print(f"Middle dimension (axis 1): {TENSOR.shape[1]} - Number of rows per matrix")
print(f"Inner dimension (axis 2): {TENSOR.shape[2]} - Number of columns per row")

# Real-world analogy: This could represent:
# - A single grayscale image patch (1 channel, 3x3 pixels)
# - One time step of a 3x3 feature map in a CNN
# - A small kernel/filter in convolutional operations
# - A single sample in a batch of 3x3 matrices

TENSOR

3D Tensor:
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
Data type: torch.int64
Dimension: 3
Shape: torch.Size([1, 3, 3])
Number of dimensions: 3
Total elements: 9

Dimensional analysis:
Outer dimension (axis 0): 1 - Number of 3x3 matrices
Middle dimension (axis 1): 3 - Number of rows per matrix
Inner dimension (axis 2): 3 - Number of columns per row


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

## **5. Specialized Tensor Initialization Methods**

### **5.1 Zero and One Initialization**

**Theoretical Background:**
Zero and one tensors serve crucial roles in deep learning applications:

#### **5.1.1 Zero Tensors**
- **Mathematical representation**: **0** ∈ ℝᵈ¹ˣᵈ²ˣ...ˣᵈⁿ where all elements equal 0
- **Applications**:
  - **Bias initialization**: Starting with zero bias in neural networks
  - **Padding operations**: Adding zero-valued boundaries to tensors
  - **Masking**: Creating attention masks or sequence padding
  - **Memory allocation**: Pre-allocating tensors before filling with computed values

#### **5.1.2 One Tensors**  
- **Mathematical representation**: **1** ∈ ℝᵈ¹ˣᵈ²ˣ...ˣᵈⁿ where all elements equal 1
- **Applications**:
  - **Identity operations**: Creating identity matrices for linear algebra
  - **Normalization**: Serving as multiplicative identity elements
  - **Template creation**: Base tensors for subsequent operations
  - **Testing**: Simplified computations for debugging and validation

In [40]:
# Create a tensor filled with zeros using torch.zeros()
# The size parameter determines the tensor dimensions
# This is essential for initializing tensors before computation

zeros = torch.zeros(size=(3, 4))  # Create a 3x4 matrix of zeros

print(f"Zero tensor:\n{zeros}")
print(f"Shape: {zeros.shape}")
print(f"Data type: {zeros.dtype}")  # Default is torch.float32
print(f"Device: {zeros.device}")    # Default is CPU
print(f"Total elements: {zeros.numel()}")

# Memory and computational considerations:
print(f"\nTensor properties:")
print(f"Memory usage (bytes): {zeros.element_size() * zeros.numel()}")
print(f"Is contiguous in memory: {zeros.is_contiguous()}")
print(f"Requires gradient: {zeros.requires_grad}")

# Common use cases for zero tensors:
# 1. Neural network bias initialization: bias = torch.zeros(output_features)
# 2. Attention masks: mask = torch.zeros(seq_len, seq_len)
# 3. Gradient accumulation: grad_accumulator = torch.zeros_like(parameter)
# 4. Batch processing placeholders: batch_data = torch.zeros(batch_size, features)

# Mathematical verification:
print(f"\nMathematical properties:")
print(f"Sum of all elements: {torch.sum(zeros).item()}")
print(f"Mean of all elements: {torch.mean(zeros).item()}")
print(f"Standard deviation: {torch.std(zeros).item()}")

zeros, zeros.dtype

Zero tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape: torch.Size([3, 4])
Data type: torch.float32
Device: cpu
Total elements: 12

Tensor properties:
Memory usage (bytes): 48
Is contiguous in memory: True
Requires gradient: False

Mathematical properties:
Sum of all elements: 0.0
Mean of all elements: 0.0
Standard deviation: 0.0


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [41]:
# Create a tensor filled with ones using torch.ones()
# Similar to zeros, but all elements are initialized to 1.0
# Useful for multiplicative identity operations and normalization

ones = torch.ones(size=(3, 4))  # Create a 3x4 matrix of ones

print(f"Ones tensor:\n{ones}")
print(f"Shape: {ones.shape}")
print(f"Data type: {ones.dtype}")  # Default is torch.float32
print(f"Device: {ones.device}")

# Mathematical properties of ones tensor:
print(f"\nMathematical analysis:")
print(f"Sum of all elements: {torch.sum(ones).item()}")  # Should equal total elements
print(f"Product of all elements: {torch.prod(ones).item()}")  # Should equal 1.0
print(f"Mean of all elements: {torch.mean(ones).item()}")  # Should equal 1.0
print(f"L2 norm: {torch.norm(ones).item():.4f}")  # Square root of number of elements

# Practical applications:
# 1. Identity matrix creation: I = torch.eye(n) or torch.ones(n,n) with modifications
# 2. Masking operations: valid_mask = torch.ones(sequence_length)
# 3. Weight initialization scaling: weights = torch.ones(shape) * init_scale
# 4. Attention mechanisms: attention_weights = torch.ones(num_heads, seq_len, seq_len)

# Computational efficiency note:
# Both zeros() and ones() are optimized operations that don't require
# element-by-element assignment, making them very fast for large tensors

ones, ones.dtype

Ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Shape: torch.Size([3, 4])
Data type: torch.float32
Device: cpu

Mathematical analysis:
Sum of all elements: 12.0
Product of all elements: 1.0
Mean of all elements: 1.0
L2 norm: 3.4641


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### **5.2 Random Tensor Generation**

**Theoretical Foundation:**
Random tensors are fundamental in machine learning for:

1. **Parameter Initialization**: Breaking symmetry in neural networks
2. **Stochastic Processes**: Modeling uncertainty and variability  
3. **Data Augmentation**: Creating synthetic training examples
4. **Monte Carlo Methods**: Approximating complex probability distributions

#### **5.2.1 Uniform Random Distribution**

The [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) function generates tensors with values sampled from a uniform distribution over the interval [0, 1):

**Mathematical representation**: X ~ U(0,1)
- **Probability density function**: f(x) = 1 for x ∈ [0,1), 0 otherwise
- **Mean**: μ = 0.5
- **Variance**: σ² = 1/12 ≈ 0.083

In [42]:
# Create a tensor with random values from uniform distribution [0, 1)
# Random tensors are crucial for neural network weight initialization
# They help break symmetry and enable effective learning

random_tensor = torch.rand(size=(3, 4))  # 3x4 matrix with random values

print(f"Random tensor:\n{random_tensor}")
print(f"Shape: {random_tensor.shape}")
print(f"Data type: {random_tensor.dtype}")

# Statistical analysis of the random tensor:
print(f"\nStatistical properties:")
print(f"Minimum value: {torch.min(random_tensor).item():.6f}")
print(f"Maximum value: {torch.max(random_tensor).item():.6f}")
print(f"Mean value: {torch.mean(random_tensor).item():.6f}")  # Should be ~0.5
print(f"Standard deviation: {torch.std(random_tensor).item():.6f}")  # Should be ~0.289

# Theoretical vs. empirical comparison:
# For uniform distribution U(0,1): theoretical_mean = 0.5, theoretical_std = 1/√12 ≈ 0.289
theoretical_std = 1.0 / (12**0.5)
print(f"Theoretical std for U(0,1): {theoretical_std:.6f}")

# Applications in deep learning:
# 1. Weight initialization: weights = torch.rand(input_size, output_size) * scale
# 2. Dropout simulation: dropout_mask = (torch.rand(size) > dropout_rate).float()
# 3. Data augmentation: noise = torch.rand(data.shape) * noise_level
# 4. Monte Carlo sampling: samples = torch.rand(num_samples, dimensions)

# Note: Each execution will produce different values due to randomness
# This is essential for stochastic training processes in machine learning

random_tensor, random_tensor.dtype

Random tensor:
tensor([[0.1707, 0.6598, 0.0077, 0.1625],
        [0.5600, 0.3164, 0.2570, 0.6037],
        [0.6397, 0.9936, 0.9622, 0.2365]])
Shape: torch.Size([3, 4])
Data type: torch.float32

Statistical properties:
Minimum value: 0.007692
Maximum value: 0.993574
Mean value: 0.464137
Standard deviation: 0.320251
Theoretical std for U(0,1): 0.288675


(tensor([[0.1707, 0.6598, 0.0077, 0.1625],
         [0.5600, 0.3164, 0.2570, 0.6037],
         [0.6397, 0.9936, 0.9622, 0.2365]]),
 torch.float32)

In [43]:
# Create a random tensor with image-like dimensions
# Common computer vision tensor shape: (height, width, channels)
# This simulates a standard 224x224 RGB image used in many CV models

random_image_size_tensor = torch.rand(size=(224, 224, 3))

print(f"Image tensor shape: {random_image_size_tensor.shape}")
print(f"Number of dimensions: {random_image_size_tensor.ndim}")
print(f"Total elements: {random_image_size_tensor.numel():,}")  # Format with commas

# Memory analysis for large tensors:
element_size = random_image_size_tensor.element_size()  # Bytes per element
total_memory = random_image_size_tensor.numel() * element_size
print(f"\nMemory analysis:")
print(f"Bytes per element: {element_size}")
print(f"Total memory usage: {total_memory:,} bytes ({total_memory/1024/1024:.2f} MB)")

# Dimension interpretation for computer vision:
height, width, channels = random_image_size_tensor.shape
print(f"\nImage properties:")
print(f"Height: {height} pixels")
print(f"Width: {width} pixels")
print(f"Channels: {channels} (RGB color channels)")
print(f"Total pixels: {height * width:,}")

# Standard image formats in deep learning:
# - ImageNet standard: 224x224x3 (this example)
# - CIFAR-10: 32x32x3
# - MNIST: 28x28x1 (grayscale)
# - High-resolution: 512x512x3 or larger


# Note: In practice, we often use (C, H, W) format for PyTorch models
# This tensor uses (H, W, C) format, which is common for data loading

random_image_size_tensor.shape, random_image_size_tensor.ndim

Image tensor shape: torch.Size([224, 224, 3])
Number of dimensions: 3
Total elements: 150,528

Memory analysis:
Bytes per element: 4
Total memory usage: 602,112 bytes (0.57 MB)

Image properties:
Height: 224 pixels
Width: 224 pixels
Channels: 3 (RGB color channels)
Total pixels: 50,176


(torch.Size([224, 224, 3]), 3)

### **5.3 Creating a range and tensors like**

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

`torch.arange(start, end, step)`

Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

In [44]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

In [45]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **5.4 Tensor datatypes**

In [46]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## **6 Manipulating tensors**

### **6.1 Basic operations**

In [48]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [49]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [50]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [51]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch also has a bunch of built-in functions like [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (short for multiplication) and [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) to perform basic operations.

In [52]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [53]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### **6.2 Matrix Multiplication: The Foundation of Neural Networks**

#### **6.2.1 Mathematical Definition**

For matrices **A** ∈ ℝᵐˣⁿ and **B** ∈ ℝⁿˣᵖ, their product **C** = **AB** ∈ ℝᵐˣᵖ is defined as:

C[i,j] = Σₖ₌₁ⁿ A[i,k] × B[k,j]

#### **6.2.2 Matrix Multiplication Rules and Implementation**

PyTorch implements matrix multiplication through the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) function, which handles various tensor dimensions automatically.

**Critical Rules for Matrix Multiplication:**

**Rule 1: Inner Dimension Compatibility**
The inner dimensions of the matrices must match for multiplication to be possible:
- **Valid**: (m, n) @ (n, p) → (m, p) ✓
- **Invalid**: (m, n) @ (k, p) where n ≠ k ✗

**Examples:**
- `(3, 2) @ (3, 2)` → **Invalid** (inner dimensions: 2 ≠ 3)
- `(2, 3) @ (3, 2)` → **Valid** (inner dimensions: 3 = 3) → Result: (2, 2)
- `(3, 2) @ (2, 3)` → **Valid** (inner dimensions: 2 = 2) → Result: (3, 3)

**Rule 2: Output Shape Determination**
The resulting matrix has the shape of the outer dimensions:
- (m, **n**) @ (**n**, p) → (m, p)
- The inner dimensions (**n**) are "consumed" during multiplication

**Operator Notation:**
- **Recommended**: `torch.matmul(A, B)` or `A @ B`
- **Alternative**: `torch.mm(A, B)` for 2D matrices only
- **Note**: The `@` operator is the standard Python matrix multiplication symbol (PEP 465)

**Computational Complexity:**
- **Time complexity**: O(mnp) for (m,n) @ (n,p)
- **Space complexity**: O(mp) for the result matrix
- **GPU acceleration**: Highly optimized on modern GPUs using libraries like cuBLAS

In [54]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our `tensor` variable with values `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |

In [55]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [56]:
# Demonstrate matrix multiplication using torch.matmul()
# This example shows the mathematical difference between element-wise and matrix multiplication

# Using the previously defined tensor: [1, 2, 3]
print(f"Vector tensor: {tensor}")
print(f"Vector shape: {tensor.shape}")

# Matrix multiplication for vectors computes the dot product
# Mathematical formula: v · v = Σᵢ vᵢ × vᵢ = v₁² + v₂² + v₃²
matrix_result = torch.matmul(tensor, tensor)

print(f"\n=== MATRIX MULTIPLICATION (DOT PRODUCT) ===")
print(f"Operation: torch.matmul({tensor}, {tensor})")
print(f"Mathematical computation: (1×1) + (2×2) + (3×3) = 1 + 4 + 9 = 14")
print(f"Result: {matrix_result}")
print(f"Result shape: {matrix_result.shape}")  # Scalar result (0-dimensional)
print(f"Result type: {type(matrix_result.item())} value = {matrix_result.item()}")

# Interpretation in machine learning contexts:
print(f"\n=== MACHINE LEARNING INTERPRETATIONS ===")
print("1. Similarity measure: Higher dot product indicates more similar vectors")
print("2. Energy/norm calculation: ||v||² = v·v (when v=tensor)")
print(f"3. Vector magnitude: ||v|| = √(v·v) = √{matrix_result.item()} = {torch.sqrt(matrix_result).item():.4f}")
print("4. Neural network computation: Linear layer output = input·weights")

# Computational efficiency note:
print(f"\n=== COMPUTATIONAL NOTES ===")
print("Matrix multiplication is highly optimized in PyTorch:")
print("- Uses BLAS (Basic Linear Algebra Subprograms) libraries")
print("- Automatically leverages multiple CPU cores")
print("- GPU acceleration available via cuBLAS on CUDA devices")
print("- Essential operation for neural network forward/backward passes")

matrix_result

Vector tensor: tensor([1, 2, 3])
Vector shape: torch.Size([3])

=== MATRIX MULTIPLICATION (DOT PRODUCT) ===
Operation: torch.matmul(tensor([1, 2, 3]), tensor([1, 2, 3]))
Mathematical computation: (1×1) + (2×2) + (3×3) = 1 + 4 + 9 = 14
Result: 14
Result shape: torch.Size([])
Result type: <class 'int'> value = 14

=== MACHINE LEARNING INTERPRETATIONS ===
1. Similarity measure: Higher dot product indicates more similar vectors
2. Energy/norm calculation: ||v||² = v·v (when v=tensor)
3. Vector magnitude: ||v|| = √(v·v) = √14 = 3.7417
4. Neural network computation: Linear layer output = input·weights

=== COMPUTATIONAL NOTES ===
Matrix multiplication is highly optimized in PyTorch:
- Uses BLAS (Basic Linear Algebra Subprograms) libraries
- Automatically leverages multiple CPU cores
- GPU acceleration available via cuBLAS on CUDA devices
- Essential operation for neural network forward/backward passes


tensor(14)

In [57]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

### **6.3 Aggregation**

In [58]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Sum: 450


In [60]:
print(f"Mean: {x.mean()}") # this will give error

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [61]:
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype

Mean: 45.0


> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with `torch` methods.

In [62]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### **6.4 Positional min/max**

You can also find the index of a tensor where the max or minimum occurs with [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself

In [63]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### **6.5 Reshaping, Stacking, Squeezing and Unsqueezing**

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.


| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [64]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Now let's add an extra dimension with `torch.reshape()`.

In [65]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [66]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [67]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [70]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()`

In [72]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [75]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a *view* with new `dims`.

In [76]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **Note**: Because permuting returns a *view* (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

### **6.6 Indexing**

In [78]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [82]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"\nSecond square bracket: {x[0][0]}")
print(f"\nThird square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Second square bracket: tensor([1, 2, 3])

Third square bracket: 1


You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [85]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [86]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [87]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [88]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## **7 PyTorch tensors & NumPy**